[credentials]
client_id = "user.f4d3811b-5c35-41f7-99e4-45fae5963ab7"
client_secret = "arpl7U6ug7VD5BQCzImD99353tj0BG"
email = "test@test.com"
password = "testpassword"

[server]
url = "http://localhost:8000"
